
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context:  . 
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./src:/var/www/html
    expose:
    - "9000"